'use client'

import React from "react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { DownloadIcon, PlayIcon } from "@radix-ui/react-icons";
import { PiFileAudioBold, PiFileCodeBold, PiMusicNotesBold } from "react-icons/pi";
import { GlobalContext } from "@/context/GlobalContext";

const GeneratedAudioData = () => {
    const { globalState, setGlobalState } = React.useContext(GlobalContext)

    return (
        <Card style = {{ border: 'none' }} className = "shadow-none" >
            <CardHeader>
                <CardTitle>Generated audio data</CardTitle>
                <CardDescription>
                    These files were generated by the sonification process.
                </CardDescription>
            </CardHeader>
            <CardContent>
                <div className="space-y-4">
                    <div className="grid gap-6">
                        <div className="flex items-center justify-between space-x-4">
                            <div className="flex items-center space-x-4">
                                <PiMusicNotesBold />
                                <div>
                                    <p className="text-sm font-medium leading-none">
                                        MP3
                                    </p>
                                    <p className="text-xs text-muted-foreground">{globalState.response.mp3.filename}</p>
                                </div>
                            </div>
                            <div className="flex items-center space-x-1">
                                <Button variant="secondary">
                                    <PlayIcon className="h-4 w-4 mr-1" />
                                    Play
                                </Button>
                                <Link href={globalState.response.mp3.url} target="_blank" download>
                                    <Button>
                                        <DownloadIcon className="h-4 w-4 mr-1" />
                                        Download
                                    </Button>
                                </Link>
                            </div>
                        </div>
                        <div className="flex items-center justify-between space-x-4">
                            <div className="flex items-center space-x-4">
                                <PiFileAudioBold />
                                <div>
                                    <p className="text-sm font-medium leading-none">
                                        Midi
                                    </p>
                                    <p className="text-xs text-muted-foreground">{globalState.response.midi.filename}</p>
                                </div>
                            </div>
                            <div className="flex items-center space-x-1">
                                <Button variant="secondary">
                                    <PlayIcon className="h-4 w-4 mr-1" />
                                    Play
                                </Button>
                                <Link href={globalState.response.midi.url} target="_blank" download>
                                    <Button>
                                        <DownloadIcon className="h-4 w-4 mr-1" />
                                        Download
                                    </Button>
                                </Link>
                            </div>
                        </div>
                        <div className="flex items-center justify-between space-x-4">
                            <div className="flex items-center space-x-4">
                                <PiFileCodeBold />
                                <div>
                                    <p className="text-sm font-medium leading-none">
                                        JSON
                                    </p>
                                    <p className="text-xs text-muted-foreground">{globalState.response.json.filename}</p>
                                </div>
                            </div>
                            <div className="flex items-center space-x-1">
                                <Link href={globalState.response.json.url} target="_blank" download>
                                    <Button>
                                        <DownloadIcon className="h-4 w-4 mr-1" />
                                        Download
                                    </Button>
                                </Link>
                            </div>
                        </div>
                    </div>
                </div>
            </CardContent>
        </Card>
    )
}

export default GeneratedAudioData