version: '3'

services:
  sound-of-dna-api:
    container_name: sound-of-dna-api
    build:
      context: .
      dockerfile: ../.docker/python/Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - sound-of-dna-network

networks:
  sound-of-dna-network:
    driver: bridge
